target ("test.utils")
    set_kind("static")
    add_files("test_utils.cppm", {public = true})

target("test.plugin_loader")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/test_plugin_loader.cpp")
    add_deps("avalon.core", "test.utils")

target("test.vfs")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/test_vfs.cpp")
    add_deps("avalon.core", "test.utils")
    set_rundir("$(projectdir)")

target("test.shader_compiler")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/shader_compiler/*.cpp")
    add_deps("avalon.core", "avalon.shader_compiler", "test.utils")
    set_rundir("$(projectdir)")
