
target ("test.utils")
    set_kind("static")
    add_files("test_utils.cppm", {public = true})

target("test.plugin_loader")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/test_plugin_loader.cpp")
    add_deps("avalon.core", "test.utils", "mock.plugin" )

target("test.vfs")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/test_vfs.cpp")
    add_deps("avalon.core", "test.utils")
    set_rundir("$(projectdir)")

target("test.memory")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/test_memory.cpp")
    add_deps("avalon.core", "test.utils")

target("test.shader_compiler")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/shader_compiler/*.cpp")
    add_deps("avalon.core", "avalon.shader_compiler", "test.utils")
    set_rundir("$(projectdir)")

target("test.glfw_window")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/test_glfw_window.cpp")
    add_deps("avalon.core", "avalon.window.glfw", "test.utils")

target("test.vulkan")
    set_kind("binary")
    set_group("Tests")
    add_files("unit/test_vulkan.cpp")
    add_deps("avalon.core","avalon.window.glfw", "avalon.rhi.vulkan", "test.utils")
