module;
export module avalon.core;
export import :log;
export import :status;
export import :types;
export import :plugin_loader;
export import :vfs;
export import :memory;
export import :memory.blobs;
export import :containers;
export import :containers.array;
export import :platform;
export import :ref_counted;
export import :non_copyable;
export import :utils;
export import :serialization;
